@startuml
class CameraController {
    + FollowDistance : float = 30.0f
    + MaxFollowDistance : float = 100.0f
    + MinFollowDistance : float = 2.0f
    + ElevationAngle : float = 30.0f
    + MaxElevationAngle : float = 85.0f
    + MinElevationAngle : float = 0f
    + OrbitalAngle : float = 0f
    + MovementSmoothing : bool = true
    + RotationSmoothing : bool = false
    + MovementSmoothingValue : float = 25f
    + RotationSmoothingValue : float = 5.0f
    + MoveSensitivity : float = 2.0f
}
enum CameraModes {
    Follow,
    Isometric,
    Free,
}
MonoBehaviour <|-- CameraController
CameraController --> "CameraTarget" Transform
CameraController o-> "CameraMode" CameraModes
CameraController +-- CameraModes
@enduml
