@startuml
class UIEffectCharacter {
    + RegisterEffect(name:string, effect:GameObject) : void
    + PlayEffect(name:string) : void
    + StopCurrentEffect() : void
    + IsEffectPlaying() : bool
}
MonoBehaviour <|-- UIEffectCharacter
@enduml
