@startuml
class ProgrammerSkill {
    + <<override>> Initialize(player:Player) : void
    + <<override>> Cleanup(player:Player) : void
    + <<override>> UseCareerSkill(player:Player) : void
    + <<override>> PerformAttack(player:Player) : void
    + <<override>> PerformChargeAttack(player:Player) : void
}
CareerSkillBase <|-- ProgrammerSkill
@enduml
