@startuml DUFFDUCK_FULL_SYSTEM
!theme plain
skinparam classAttributeIconSize 0
skinparam linetype polyline
hide empty members

!include ./Assets/Scripts/CameraController.puml
!include ./Assets/Scripts/DevCheat.puml
!include ./Assets/Scripts/GameManager.puml
!include ./Assets/Scripts/GameProgressData.puml
!include ./Assets/Scripts/ReadOnlyAttribute.puml
!include ./Assets/Scripts/SaveSystem.puml
!include ./Assets/Scripts/Character/Character.puml
!include ./Assets/Scripts/Effects/CareerEffectProfile.puml
!include ./Assets/Scripts/Effects/ComicEffectAutoRecycle.puml
!include ./Assets/Scripts/Effects/ComicEffectData.puml
!include ./Assets/Scripts/Effects/ComicEffectManager.puml
!include ./Assets/Scripts/Effects/ComicEffectPlayer.puml
!include ./Assets/Scripts/Effects/ComicEffectSpawner.puml
!include ./Assets/Scripts/Enum/CardType.puml
!include ./Assets/Scripts/Enum/DuckCareer.puml
!include ./Assets/Scripts/Enum/EnemyType.puml
!include ./Assets/Scripts/Enum/MapType.puml
!include ./Assets/Scripts/Scene/AssetSpawner.puml
!include ./Assets/Scripts/Scene/BackgroundLooper.puml
!include ./Assets/Scripts/Scene/EnemySpawner.puml
!include ./Assets/Scripts/Scene/MapGeneratorBase.puml
!include ./Assets/Scripts/Scene/MapGeneratorKitchen.puml
!include ./Assets/Scripts/Scene/MapGeneratorRoad.puml
!include ./Assets/Scripts/Scene/MapGeneratorSchool.puml
!include ./Assets/Scripts/Scene/SceneManager.puml
!include ./Assets/Scripts/Scene/SpawnSlot.puml
!include ./Assets/Scripts/Scene/Wall_Kill.puml
!include ./Assets/Scripts/Store/Currency.puml
!include ./Assets/Scripts/Store/StoreBase.puml
!include ./Assets/Scripts/Store/StoreExchange.puml
!include ./Assets/Scripts/Store/StoreItem.puml
!include ./Assets/Scripts/Store/StoreManager.puml
!include ./Assets/Scripts/Store/StoreMap.puml
!include ./Assets/Scripts/Store/StoreType.puml
!include ./Assets/Scripts/Store/StoreUpgrade.puml
!include ./Assets/Scripts/Store/TopCurrencyUI.puml
!include ./Assets/Scripts/System/DistanceCulling.puml
!include ./Assets/Scripts/System/MapCollectibleData.puml
!include ./Assets/Scripts/System/ObjectPoolManager.puml
!include ./Assets/Scripts/System/PerformanceManager.puml
!include ./Assets/Scripts/UI/UIManager.puml
!include ./Assets/Scripts/Character/Enemy/Enemy.puml
!include ./Assets/Scripts/Character/Enemy/EnemyData.puml
!include ./Assets/Scripts/Character/Enemy/Projectile.puml
!include ./Assets/Scripts/Character/Interface/IAttackable.puml
!include ./Assets/Scripts/Character/Interface/ICareerSwitchable.puml
!include ./Assets/Scripts/Character/Interface/ICollectable.puml
!include ./Assets/Scripts/Character/Interface/IDamageable.puml
!include ./Assets/Scripts/Character/Interface/IInteractable.puml
!include ./Assets/Scripts/Character/Interface/IMoveable.puml
!include ./Assets/Scripts/Character/Interface/ISkillUser.puml
!include ./Assets/Scripts/Character/Player/Player.puml
!include ./Assets/Scripts/Character/Player/PlayerController.puml
!include ./Assets/Scripts/Character/Player/PlayerData.puml
!include ./Assets/Scripts/Character/Player/PlayerInteract.puml
!include ./Assets/Scripts/Item/Card/Card.puml
!include ./Assets/Scripts/Item/Card/CardManager.puml
!include ./Assets/Scripts/Item/Card/CardSlotUI.puml
!include ./Assets/Scripts/Item/Card/CardUI.puml
!include ./Assets/Scripts/Item/Card/CardUIPool.puml
!include ./Assets/Scripts/Item/Card/MuscleButton.puml
!include ./Assets/Scripts/Item/Card/RandomStarterCard.puml
!include ./Assets/Scripts/Item/Collect/BuffManager.puml
!include ./Assets/Scripts/Item/Collect/CoinMagnet.puml
!include ./Assets/Scripts/Item/Collect/CoinTrailGenerator.puml
!include ./Assets/Scripts/Item/Collect/CollectibleItem.puml
!include ./Assets/Scripts/Item/Collect/CollectibleSpawner.puml
!include ./Assets/Scripts/Item/Throwable/ThrowableDropTable.puml
!include ./Assets/Scripts/Item/Throwable/ThrowableItemInfo.puml
!include ./Assets/Scripts/Item/Throwable/ThrowableSpawner.puml
!include ./Assets/Scripts/System/Interface/IObjectPool.puml
!include ./Assets/Scripts/System/Interface/ISpawn.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/CameraFollow.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/HealthBarUI.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/HUDLoad.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/MapSelectController.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/MenuUI.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/SceneUI.puml
!include ./Assets/Scripts/UI/Menu_GamePlay/ScoreUI.puml
!include ./Assets/Scripts/UI/Store/SlotUI.puml
!include ./Assets/Scripts/UI/Store/StoreUI.puml
!include ./Assets/Scripts/UI/Store/UpgradeUI.puml
@enduml